#!/bin/bash

# REQUIRED SETTINGS

####### Settings for mergerfs mount location variables #######
LocalFilesLocation="/mnt/user/crop/local" # Location for local files to be merged with rclone mount
MergerFSMountLocation="/mnt/user/crop/union" # Rclone data folder location
CloudFilesLocation="/mnt/user/crop/cloud"
CropappdataLocation="/mnt/user/appdata/crop"

####### END OF USER SETTINGS #######

git clone https://github.com/watchmeexplode5/lclone-crop-aio /mnt/user/appdata/temp
mkdir -p $CropappdataLocation/
mv /mnt/user/appdata/temp/crop $CropappdataLocation/crop
mv /mnt/user/appdata/temp/lclone $CropappdataLocation/lclone

if [[ -f "$CropappdataLocation/config.yaml" ]]; then
			echo "$(date "+%d.%m.%Y %T") INFO: Config already present - Will not override."
		else
			mv /mnt/user/appdata/temp/config.yaml $CropappdataLocation/config.yaml
fi

if [[ -f "$CropappdataLocation/rclone.conf" ]]; then
			echo "$(date "+%d.%m.%Y %T") INFO: Rclone Config already present - Will not override."
		else
			mv /mnt/user/appdata/temp/rclone.conf $CropappdataLocation/rclone.conf
fi

if [[ -f "$CropappdataLocation/service_accounts" ]]; then
			echo "$(date "+%d.%m.%Y %T") INFO: Service Account File already present - Will not override."
		else
			mv /mnt/user/appdata/temp/service_accounts $CropappdataLocation/service_accounts
fi


echo "$(date "+%d.%m.%Y %T") INFO: Removing Temp."
rm -rf /mnt/user/appdata/temp

echo "$(date "+%d.%m.%Y %T") INFO: Setting Permissions."
chmod +x $CropappdataLocation/crop
chmod +x $CropappdataLocation/lclone

if [[ -f "/bin/mergerfs" ]]; then
			echo "$(date "+%d.%m.%Y %T") INFO: Mergerfs already installed, proceeding to create mergerfs mount"
		else
# Build mergerfs binary
			echo "$(date "+%d.%m.%Y %T") INFO: Mergerfs not installed - installing now."
			mkdir -p /mnt/user/appdata/crop/mergerfs
			docker run -v /mnt/user/appdata/crop/mergerfs:/build --rm trapexit/mergerfs-static-build
			mv /mnt/user/appdata/crop/mergerfs/mergerfs /bin
# check if mergerfs install successful
			echo "$(date "+%d.%m.%Y %T") INFO: *sleeping for 5 seconds"
			sleep 5

fi

# mergerfs mount command
mergerfs $LocalFilesLocation:$CloudFilesLocation $MergerFSMountLocation -o rw,async_read=false,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=partial,dropcacheonclose=true


echo "$(date "+%d.%m.%Y %T") INFO: Script complete"

exit